const Projects = [
	{
		name: "Chess-club - 4 horses (js + scss)",
		screen: "",
		solution: "https://github.com/MIU-cz/My_works/tree/master/Yandex",
		deploy: "https://miu-cz.github.io/My_works/Yandex/",
		description: "Web for chess-club ..",
	},
	{
		name: "INIZIO Internet Media (php + js)",
		screen: "",
		solution: "https://github.com/MIU-cz/My_works/tree/master/INZIO-search-form",
		deploy: "https://miu.jecool.net/new_sites/INZIO-search-form/index.html",
		description: "GOOGLE search parser results",
	},
	{
		name: "FAPI Business (php + js)",
		screen: "",
		solution: "https://github.com/MIU-cz/My_works/tree/master/FAPI-currency-form",
		deploy: "https://miu.jecool.net/new_sites/FAPI-currency-form/index.html",
		description: "Order form & convert exchenge",
	},
	{
		name: "VVM-ipso - v2 (php + js + scss)",
		screen: "",
		solution: "https://github.com/MIU-cz/My_works/tree/master/marf-vvm-v2",
		deploy: "http://miu.jecool.net/new_sites/marf-vvm-v2/index.php",
		description: "Web for chess-club ..",
	},
	{
		name: "MARF-TRAVEL (php + mySQL)",
		screen: "",
		solution: "https://github.com/MIU-cz/My_works/tree/master/marf-Tour",
		deploy: "http://miu.jecool.net/new_sites/marf-Tour/",
		description: "Test tour-page with admin concole + cocie + session",
	},
	{
		name: "Kalendar",
		screen: "",
		solution: "https://github.com/MIU-cz/PHP-Work/tree/main/Kalendar",
		deploy: "http://miu.jecool.net/new_sites/Kalendar/index.php",
		description: "Kalendar & tasks",
	},
	{
		name: "convers csv to mySQL",
		screen: "",
		solution: "https://github.com/MIU-cz/PHP-Work/tree/main/3IT-php-test",
		deploy: "http://miu.jecool.net/new_sites/3IT-php-test/index.php",
		description: "add data to database & sort",
	},
	{
		name: "Age calculator app solution",
		screen: "",
		solution: "https://github.com/MIU-cz/FrontEnd-Mentor-projects/tree/main/age-calc",
		deploy: "https://miu-cz.github.io/FrontEnd-Mentor-projects/age-calc/",
		description: "app solution",
	},
	{
		name: "Loopstudios landing page solution",
		screen: "",
		solution: "https://github.com/MIU-cz/FrontEnd-Mentor-projects/tree/main/loopstudios-landing-page-main",
		deploy: "https://miu-cz.github.io/FrontEnd-Mentor-projects/loopstudios-landing-page-main/",
		description: "landing page",
	},
	{
		name: "Blogr landing page solution",
		screen: "",
		solution: "https://github.com/MIU-cz/FrontEnd-Mentor-projects/tree/main/blogr-landing-page",
		deploy: "https://miu-cz.github.io/FrontEnd-Mentor-projects/blogr-landing-page/",
		description: "landing page",
	},
];
